USE final_proj;

-- insercao de valores pais
INSERT INTO country VALUES (default, "ALEMANHA");
INSERT INTO country VALUES (default, "ARABIA");
INSERT INTO country VALUES (default, "BRASIL");
INSERT INTO country VALUES (default, "CHINA");
INSERT INTO country VALUES (default, "ESPANHA");
INSERT INTO country VALUES (default, "FRANCA");
INSERT INTO country VALUES (default, "INDIA");
INSERT INTO country VALUES (default, "ITALIA");
INSERT INTO country VALUES (default, "JAPAO");
INSERT INTO country VALUES (default, "MEXICO");

SELECT * FROM country;


-- insercao de valores restaurante
INSERT INTO restaurant VALUES (default, "DIE MEISTER STUBE", 1, default);
INSERT INTO restaurant VALUES (default, "JUCA LEMAO", 1, default);
INSERT INTO restaurant VALUES (default, "KLEINE-GASSE", 1, default);
INSERT INTO restaurant VALUES (default, "SCHNAPSHAUS", 1, default);
INSERT INTO restaurant VALUES (default, "WINDHUK", 1, default);
INSERT INTO restaurant VALUES (default, "ZUR ALTEN MUHLE", 1, default);
INSERT INTO restaurant VALUES (default, "ABOUD SHAWARMA & COMIDA ARABE", 2, default);
INSERT INTO restaurant VALUES (default, "ALMANARA", 2, default);
INSERT INTO restaurant VALUES (default, "ARABEK PAMPLONA", 2, default);
INSERT INTO restaurant VALUES (default, "FARABBUD MOEMA", 2, default);
INSERT INTO restaurant VALUES (default, "MOUNT ZION VEGAN", 2, default);
INSERT INTO restaurant VALUES (default, "ROSIMA", 2, default);
INSERT INTO restaurant VALUES (default, "SONHO ARABE", 2, default);
INSERT INTO restaurant VALUES (default, "ZAIN", 2, default);
INSERT INTO restaurant VALUES (default, "A CASA DO PORCO", 3, default);
INSERT INTO restaurant VALUES (default, "ARTURITO", 3, default);
INSERT INTO restaurant VALUES (default, "CORRUTELA", 3, default);
INSERT INTO restaurant VALUES (default, "D.O.M", 3, default);
INSERT INTO restaurant VALUES (default, "MANÍ", 3, default);
INSERT INTO restaurant VALUES (default, "MANU", 3, default);
INSERT INTO restaurant VALUES (default, "MOCOTÓ", 3, default);
INSERT INTO restaurant VALUES (default, "OTEQUE", 3, default);
INSERT INTO restaurant VALUES (default, "TUJU", 3, default);
INSERT INTO restaurant VALUES (default, "CHA YE", 4, default);
INSERT INTO restaurant VALUES (default, "CHINA LAKE", 4, default);
INSERT INTO restaurant VALUES (default, "HONG BIN", 4, default);
INSERT INTO restaurant VALUES (default, "HOU CULINARIA CHINESA", 4, default);
INSERT INTO restaurant VALUES (default, "RONG HE", 4, default);
INSERT INTO restaurant VALUES (default, "TAIZAN", 4, default);
INSERT INTO restaurant VALUES (default, "TON HOI", 4, default);
INSERT INTO restaurant VALUES (default, "ADEGA SANTIAGO", 5, default);
INSERT INTO restaurant VALUES (default, "CORRIENTES 348", 5, default);
INSERT INTO restaurant VALUES (default, "MARIPILI", 5, default);
INSERT INTO restaurant VALUES (default, "TANIT", 5, default);
INSERT INTO restaurant VALUES (default, "TORERO VALESE", 5, default);
INSERT INTO restaurant VALUES (default, "VERISSIMO", 5, default);
INSERT INTO restaurant VALUES (default, "BISTRO PARIS 6", 6, default);
INSERT INTO restaurant VALUES (default, "CHEF ROUGE BISTROT GOURMAND", 6, default);
INSERT INTO restaurant VALUES (default, "LA TAMBOUILLE", 6, default);
INSERT INTO restaurant VALUES (default, "LE JAZZ BRASSERIE", 6, default);
INSERT INTO restaurant VALUES (default, "RUELLA", 6, default);
INSERT INTO restaurant VALUES (default, "TARTELIER PATISSERIE", 6, default);
INSERT INTO restaurant VALUES (default, "TONTON", 6, default);
INSERT INTO restaurant VALUES (default, "BAWARCHI", 7, default);
INSERT INTO restaurant VALUES (default, "CASA PREMA", 7, default);
INSERT INTO restaurant VALUES (default, "GOGO CURRY KAZU", 7, default);
INSERT INTO restaurant VALUES (default, "REETNAMASTE", 7, default);
INSERT INTO restaurant VALUES (default, "ROHAN RESTAURANTE", 7, default);
INSERT INTO restaurant VALUES (default, "TANDOOR", 7, default);
INSERT INTO restaurant VALUES (default, "TULSI INDIAN CUISINE", 7, default);
INSERT INTO restaurant VALUES (default, "BACIO DI LATTE", 8, default);
INSERT INTO restaurant VALUES (default, "ELLE 5", 8, default);
INSERT INTO restaurant VALUES (default, "LA BRACIERA PIZZA NAPOLETANA", 8, default);
INSERT INTO restaurant VALUES (default, "OSTERIA GENERALE", 8, default);
INSERT INTO restaurant VALUES (default, "RISTORANTINO", 8, default);
INSERT INTO restaurant VALUES (default, "SOGGIORNO", 8, default);
INSERT INTO restaurant VALUES (default, "SUPRA DI MAURO MAIA", 8, default);
INSERT INTO restaurant VALUES (default, "DAIKI SUSHI", 9, default);
INSERT INTO restaurant VALUES (default, "DJAPA", 9, default);
INSERT INTO restaurant VALUES (default, "MANIHI SUSHI", 9, default);
INSERT INTO restaurant VALUES (default, "OHKA", 9, default);
INSERT INTO restaurant VALUES (default, "PEIXE AO CUBO", 9, default);
INSERT INTO restaurant VALUES (default, "SAPPORO", 9, default);
INSERT INTO restaurant VALUES (default, "SASSÁ SUSHI", 9, default);
INSERT INTO restaurant VALUES (default, "SUSHIMAR", 9, default);
INSERT INTO restaurant VALUES (default, "DON PANCHO", 10, default);
INSERT INTO restaurant VALUES (default, "EXQUISITO!", 10, default);
INSERT INTO restaurant VALUES (default, "HABANERO", 10, default);
INSERT INTO restaurant VALUES (default, "MEXICANÍSSIMO", 10, default);
INSERT INTO restaurant VALUES (default, "SI SEÑOR", 10, default);
INSERT INTO restaurant VALUES (default, "TAQUERÍA LA SABROSA", 10, default);
INSERT INTO restaurant VALUES (default, "YUCATAN", 10, default);

SELECT * FROM restaurant;


-- insercao de pratos
INSERT INTO meals VALUES (default, "APFELSTRUDEL", 1);
INSERT INTO meals VALUES (default, "APFELWEIN", 1);
INSERT INTO meals VALUES (default, "BRATHEND’L", 1);
INSERT INTO meals VALUES (default, "BRETZEL", 1);
INSERT INTO meals VALUES (default, "CHUCRUTE (SAUERKRAUT)", 1);
INSERT INTO meals VALUES (default, "CURRYWURST COM BATATAS", 1);
INSERT INTO meals VALUES (default, "DRESDNER STOLLEN", 1);
INSERT INTO meals VALUES (default, "EINTOPF", 1);
INSERT INTO meals VALUES (default, "EISBEIN", 1);
INSERT INTO meals VALUES (default, "FLAMMKUCHEN", 1);
INSERT INTO meals VALUES (default, "FLEISCHKÄSE", 1);
INSERT INTO meals VALUES (default, "GRÜTZE ROTE", 1);
INSERT INTO meals VALUES (default, "KARTOFFELPUFFER", 1);
INSERT INTO meals VALUES (default, "KARTOFFELSALAT", 1);
INSERT INTO meals VALUES (default, "LEBKUCHEN", 1);
INSERT INTO meals VALUES (default, "SAUERKRAUT", 1);
INSERT INTO meals VALUES (default, "SCHNEEBALLEN", 1);
INSERT INTO meals VALUES (default, "SCHNITZEL", 1);
INSERT INTO meals VALUES (default, "SCHWARZWÄLDER KIRSCHTORTE", 1);
INSERT INTO meals VALUES (default, "SCHWEINEBRATEN", 1);
INSERT INTO meals VALUES (default, "STRUDEL DE MAÇÃ", 1);
INSERT INTO meals VALUES (default, "WURST", 1);
INSERT INTO meals VALUES (default, "ARAYESS", 2);
INSERT INTO meals VALUES (default, "ATAIF", 2);
INSERT INTO meals VALUES (default, "BABAGHANOUSH", 2);
INSERT INTO meals VALUES (default, "BAKLAWA", 2);
INSERT INTO meals VALUES (default, "FALAFEL", 2);
INSERT INTO meals VALUES (default, "FATUSH", 2);
INSERT INTO meals VALUES (default, "HARIRA", 2);
INSERT INTO meals VALUES (default, "HOMMUS BI TAHINE", 2);
INSERT INTO meals VALUES (default, "KABSA", 2);
INSERT INTO meals VALUES (default, "KAFTA", 2);
INSERT INTO meals VALUES (default, "KIBBEH", 2);
INSERT INTO meals VALUES (default, "KIBBEH NAYE", 2);
INSERT INTO meals VALUES (default, "MAMUL", 2);
INSERT INTO meals VALUES (default, "MAQLUBA", 2);
INSERT INTO meals VALUES (default, "MURTABAK", 2);
INSERT INTO meals VALUES (default, "SHAWARMA", 2);
INSERT INTO meals VALUES (default, "TABBULEH", 2);
INSERT INTO meals VALUES (default, "ACARAJÉ", 3);
INSERT INTO meals VALUES (default, "ARROZ CARRETEIRO", 3);
INSERT INTO meals VALUES (default, "ARROZ COM PEQUI", 3);
INSERT INTO meals VALUES (default, "BAIÃO DE DOIS", 3);
INSERT INTO meals VALUES (default, "BARREADO", 3);
INSERT INTO meals VALUES (default, "BOBÓ DE CAMARÃO", 3);
INSERT INTO meals VALUES (default, "CALDO DE PIRANHA", 3);
INSERT INTO meals VALUES (default, "CAMARÃO NA MORANGA", 3);
INSERT INTO meals VALUES (default, "ENTREVERO DE PINHÃO", 3);
INSERT INTO meals VALUES (default, "FAROFA DE BANANA", 3);
INSERT INTO meals VALUES (default, "FEIJÃO TROPEIRO", 3);
INSERT INTO meals VALUES (default, "FEIJOADA", 3);
INSERT INTO meals VALUES (default, "FRANGO AO MOLHO PARDO", 3);
INSERT INTO meals VALUES (default, "GALINHADA", 3);
INSERT INTO meals VALUES (default, "MOQUECA DE PEIXE", 3);
INSERT INTO meals VALUES (default, "PAÇOCA DE CARNE SECA", 3);
INSERT INTO meals VALUES (default, "PATO NO TUCUPI", 3);
INSERT INTO meals VALUES (default, "RABADA", 3);
INSERT INTO meals VALUES (default, "TACACÁ", 3);
INSERT INTO meals VALUES (default, "TAMBAQUI ASSADO", 3);
INSERT INTO meals VALUES (default, "TUTU DE FEIJÃO", 3);
INSERT INTO meals VALUES (default, "VATAPÁ", 3);
INSERT INTO meals VALUES (default, "VIRADO À PAULISTA", 3);
INSERT INTO meals VALUES (default, "ARROZ FRITO", 4);
INSERT INTO meals VALUES (default, "BANANA CARAMELADA", 4);
INSERT INTO meals VALUES (default, "DAN DAN MIAN", 4);
INSERT INTO meals VALUES (default, "DUMPLING", 4);
INSERT INTO meals VALUES (default, "FRANGO DO GENERAL TSO", 4);
INSERT INTO meals VALUES (default, "FRANGO XADREZ", 4);
INSERT INTO meals VALUES (default, "GUA-BAO", 4);
INSERT INTO meals VALUES (default, "GUIOZA", 4);
INSERT INTO meals VALUES (default, "HARUMAKI", 4);
INSERT INTO meals VALUES (default, "MACARRÃO CHOP SUEY", 4);
INSERT INTO meals VALUES (default, "MAPO TOFU", 4);
INSERT INTO meals VALUES (default, "NIOU ROU MIEN", 4);
INSERT INTO meals VALUES (default, "OVO MILENAR", 4);
INSERT INTO meals VALUES (default, "PATO À PEQUIM", 4);
INSERT INTO meals VALUES (default, "TIAN BU LA", 4);
INSERT INTO meals VALUES (default, "WONTON", 4);
INSERT INTO meals VALUES (default, "YAKISSOBA", 4);
INSERT INTO meals VALUES (default, "ZONG ZI", 4);
INSERT INTO meals VALUES (default, "CHURROS", 5);
INSERT INTO meals VALUES (default, "COCIDO MADRILEÑO", 5);
INSERT INTO meals VALUES (default, "CROQUETAS", 5);
INSERT INTO meals VALUES (default, "FABADA ASTURIANA", 5);
INSERT INTO meals VALUES (default, "GAZPACHO", 5);
INSERT INTO meals VALUES (default, "JAMÓN", 5);
INSERT INTO meals VALUES (default, "MARZIPÃ", 5);
INSERT INTO meals VALUES (default, "PAELLA ", 5);
INSERT INTO meals VALUES (default, "PAN CON TOMATE", 5);
INSERT INTO meals VALUES (default, "PATATAS BRAVAS", 5);
INSERT INTO meals VALUES (default, "PINCHOS", 5);
INSERT INTO meals VALUES (default, "PISTO", 5);
INSERT INTO meals VALUES (default, "PULPO A LA GALLEGA", 5);
INSERT INTO meals VALUES (default, "TAPAS ESPAÑOLAS", 5);
INSERT INTO meals VALUES (default, "TORRIJAS", 5);
INSERT INTO meals VALUES (default, "TORTILLA DE PATATA", 5);
INSERT INTO meals VALUES (default, "BOEUF BOURGUIGNON", 6);
INSERT INTO meals VALUES (default, "CASSOULET", 6);
INSERT INTO meals VALUES (default, "CONFIT DE CANARD", 6);
INSERT INTO meals VALUES (default, "COQ AU VIN", 6);
INSERT INTO meals VALUES (default, "CROISSANT", 6);
INSERT INTO meals VALUES (default, "CROQUE MONSIEUR", 6);
INSERT INTO meals VALUES (default, "ESCALOPE DE VEAU A LA CREME ET AUX CHAMPIGNONS", 6);
INSERT INTO meals VALUES (default, "FONDUE BOURGUIGNONNE", 6);
INSERT INTO meals VALUES (default, "LA BOUILLABAISSE MARSEILLAISE", 6);
INSERT INTO meals VALUES (default, "MACARONS", 6);
INSERT INTO meals VALUES (default, "MADELEINE", 6);
INSERT INTO meals VALUES (default, "MAGRET DE CANARD", 6);
INSERT INTO meals VALUES (default, "MOULES FRITES", 6);
INSERT INTO meals VALUES (default, "MOUSSE AU CHOCOLAT NOIR", 6);
INSERT INTO meals VALUES (default, "PETIT GÂTEAU", 6);
INSERT INTO meals VALUES (default, "POT AU FEU", 6);
INSERT INTO meals VALUES (default, "POULET FRITES", 6);
INSERT INTO meals VALUES (default, "PROFITEROLE", 6);
INSERT INTO meals VALUES (default, "RACLETTE", 6);
INSERT INTO meals VALUES (default, "RATATOUILLE", 6);
INSERT INTO meals VALUES (default, "TARTIFLETTE", 6);
INSERT INTO meals VALUES (default, "TEURGOULE", 6);
INSERT INTO meals VALUES (default, "CARIL DE PEIXE", 7);
INSERT INTO meals VALUES (default, "CHOWMEIN", 7);
INSERT INTO meals VALUES (default, "CURRY DE PEIXE", 7);
INSERT INTO meals VALUES (default, "DAL", 7);
INSERT INTO meals VALUES (default, "FRANGO TANDOORI", 7);
INSERT INTO meals VALUES (default, "FRANGO TIKKA MASALA", 7);
INSERT INTO meals VALUES (default, "GARLIC PANEER TIKKA", 7);
INSERT INTO meals VALUES (default, "GULAB JAMUN", 7);
INSERT INTO meals VALUES (default, "KHEER", 7);
INSERT INTO meals VALUES (default, "MURG MAKHANI", 7);
INSERT INTO meals VALUES (default, "NAAN", 7);
INSERT INTO meals VALUES (default, "PALAK PANEER", 7);
INSERT INTO meals VALUES (default, "RAJMA MASALA", 7);
INSERT INTO meals VALUES (default, "SAMOSA", 7);
INSERT INTO meals VALUES (default, "ARANCINO", 8);
INSERT INTO meals VALUES (default, "BISTECCA ALLA FIORENTINA", 8);
INSERT INTO meals VALUES (default, "BUCATINI ALL’AMATRICIANA", 8);
INSERT INTO meals VALUES (default, "CANNOLO", 8);
INSERT INTO meals VALUES (default, "COTOLETTA ALLA MILANESE", 8);
INSERT INTO meals VALUES (default, "GELATTO", 8);
INSERT INTO meals VALUES (default, "LASAGNA", 8);
INSERT INTO meals VALUES (default, "OLIVE ASCOLANE", 8);
INSERT INTO meals VALUES (default, "PIADINA ROMAGNOLA", 8);
INSERT INTO meals VALUES (default, "PIZZA", 8);
INSERT INTO meals VALUES (default, "POLPETTONE", 8);
INSERT INTO meals VALUES (default, "PORCHETTA", 8);
INSERT INTO meals VALUES (default, "RAVIOLI", 8);
INSERT INTO meals VALUES (default, "RISOTTO", 8);
INSERT INTO meals VALUES (default, "SPAGHETTI", 8);
INSERT INTO meals VALUES (default, "STRUFFOLI", 8);
INSERT INTO meals VALUES (default, "TIRAMISÙ", 8);
INSERT INTO meals VALUES (default, "TRIPPA ALLA ROMANA", 8);
INSERT INTO meals VALUES (default, "ENGUIA", 9);
INSERT INTO meals VALUES (default, "KARAAAGUE", 9);
INSERT INTO meals VALUES (default, "KOBE BEEF", 9);
INSERT INTO meals VALUES (default, "LAMÉM", 9);
INSERT INTO meals VALUES (default, "MELON PAN", 9);
INSERT INTO meals VALUES (default, "MISSOSHIRU", 9);
INSERT INTO meals VALUES (default, "MOTI", 9);
INSERT INTO meals VALUES (default, "NIGUIRI", 9);
INSERT INTO meals VALUES (default, "ODEN", 9);
INSERT INTO meals VALUES (default, "OKONOMIYAKI", 9);
INSERT INTO meals VALUES (default, "OMU-RAISU", 9);
INSERT INTO meals VALUES (default, "SASHIMI", 9);
INSERT INTO meals VALUES (default, "SHABU-SHABU", 9);
INSERT INTO meals VALUES (default, "SUSHI", 9);
INSERT INTO meals VALUES (default, "TAKOYAKI", 9);
INSERT INTO meals VALUES (default, "TEMAKI", 9);
INSERT INTO meals VALUES (default, "TEMPURÁ", 9);
INSERT INTO meals VALUES (default, "TONKATSU", 9);
INSERT INTO meals VALUES (default, "YAKINIKU", 9);
INSERT INTO meals VALUES (default, "YAKITORI", 9);
INSERT INTO meals VALUES (default, "TORTILLAS", 10);
INSERT INTO meals VALUES (default, "MOLE POBLANO", 10);
INSERT INTO meals VALUES (default, "POZOLE", 10);
INSERT INTO meals VALUES (default, "COCHINITA PIBIL", 10);
INSERT INTO meals VALUES (default, "TAMALES", 10);
INSERT INTO meals VALUES (default, "CHILES EN NOGADA", 10);
INSERT INTO meals VALUES (default, "CHILAQUILES", 10);
INSERT INTO meals VALUES (default, "ELOTE", 10);
INSERT INTO meals VALUES (default, "TACOS AL PASTOR", 10);
INSERT INTO meals VALUES (default, "ENCHILADAS", 10);
INSERT INTO meals VALUES (default, "ENMOLADA", 10);
INSERT INTO meals VALUES (default, "CEMITA POBLANA", 10);
INSERT INTO meals VALUES (default, "NACHOS", 10);
INSERT INTO meals VALUES (default, "TACOS", 10);
INSERT INTO meals VALUES (default, "BURRITOS", 10);
INSERT INTO meals VALUES (default, "GUACAMOLE", 10);
INSERT INTO meals VALUES (default, "MIXIOTE", 10);

SELECT * FROM meals;


-- inserçao de pratos por restaurante
INSERT INTO meals_restaurant VALUES (19, 2, default);
INSERT INTO meals_restaurant VALUES (18, 6, default);
INSERT INTO meals_restaurant VALUES (1, 2, default);
INSERT INTO meals_restaurant VALUES (6, 5, default);
INSERT INTO meals_restaurant VALUES (11, 3, default);
INSERT INTO meals_restaurant VALUES (7, 1, default);
INSERT INTO meals_restaurant VALUES (8, 3, default);
INSERT INTO meals_restaurant VALUES (17, 2, default);
INSERT INTO meals_restaurant VALUES (16, 6, default);
INSERT INTO meals_restaurant VALUES (13, 2, default);
INSERT INTO meals_restaurant VALUES (14, 4, default);
INSERT INTO meals_restaurant VALUES (3, 3, default);
INSERT INTO meals_restaurant VALUES (11, 2, default);
INSERT INTO meals_restaurant VALUES (2, 5, default);
INSERT INTO meals_restaurant VALUES (19, 1, default);
INSERT INTO meals_restaurant VALUES (16, 5, default);
INSERT INTO meals_restaurant VALUES (5, 2, default);
INSERT INTO meals_restaurant VALUES (8, 5, default);
INSERT INTO meals_restaurant VALUES (8, 6, default);
INSERT INTO meals_restaurant VALUES (17, 5, default);
INSERT INTO meals_restaurant VALUES (26, 6, default);
INSERT INTO meals_restaurant VALUES (5, 1, default);
INSERT INTO meals_restaurant VALUES (26, 3, default);
INSERT INTO meals_restaurant VALUES (21, 3, default);
INSERT INTO meals_restaurant VALUES (5, 6, default);
INSERT INTO meals_restaurant VALUES (4, 5, default);
INSERT INTO meals_restaurant VALUES (19, 5, default);
INSERT INTO meals_restaurant VALUES (9, 6, default);
INSERT INTO meals_restaurant VALUES (17, 3, default);
INSERT INTO meals_restaurant VALUES (16, 3, default);
INSERT INTO meals_restaurant VALUES (26, 4, default);
INSERT INTO meals_restaurant VALUES (6, 2, default);
INSERT INTO meals_restaurant VALUES (4, 3, default);
INSERT INTO meals_restaurant VALUES (12, 6, default);
INSERT INTO meals_restaurant VALUES (3, 4, default);
INSERT INTO meals_restaurant VALUES (3, 1, default);
INSERT INTO meals_restaurant VALUES (24, 8, default);
INSERT INTO meals_restaurant VALUES (32, 13, default);
INSERT INTO meals_restaurant VALUES (33, 11, default);
INSERT INTO meals_restaurant VALUES (24, 11, default);
INSERT INTO meals_restaurant VALUES (29, 7, default);
INSERT INTO meals_restaurant VALUES (23, 7, default);
INSERT INTO meals_restaurant VALUES (35, 8, default);
INSERT INTO meals_restaurant VALUES (29, 11, default);
INSERT INTO meals_restaurant VALUES (29, 10, default);
INSERT INTO meals_restaurant VALUES (29, 9, default);
INSERT INTO meals_restaurant VALUES (38, 14, default);
INSERT INTO meals_restaurant VALUES (32, 14, default);
INSERT INTO meals_restaurant VALUES (25, 11, default);
INSERT INTO meals_restaurant VALUES (36, 10, default);
INSERT INTO meals_restaurant VALUES (30, 9, default);
INSERT INTO meals_restaurant VALUES (38, 13, default);
INSERT INTO meals_restaurant VALUES (36, 9, default);
INSERT INTO meals_restaurant VALUES (31, 9, default);
INSERT INTO meals_restaurant VALUES (23, 13, default);
INSERT INTO meals_restaurant VALUES (30, 14, default);
INSERT INTO meals_restaurant VALUES (37, 11, default);
INSERT INTO meals_restaurant VALUES (32, 12, default);
INSERT INTO meals_restaurant VALUES (26, 14, default);
INSERT INTO meals_restaurant VALUES (31, 8, default);
INSERT INTO meals_restaurant VALUES (27, 10, default);
INSERT INTO meals_restaurant VALUES (26, 12, default);
INSERT INTO meals_restaurant VALUES (37, 10, default);
INSERT INTO meals_restaurant VALUES (38, 10, default);
INSERT INTO meals_restaurant VALUES (35, 12, default);
INSERT INTO meals_restaurant VALUES (30, 7, default);
INSERT INTO meals_restaurant VALUES (35, 13, default);
INSERT INTO meals_restaurant VALUES (25, 12, default);
INSERT INTO meals_restaurant VALUES (30, 10, default);
INSERT INTO meals_restaurant VALUES (25, 14, default);
INSERT INTO meals_restaurant VALUES (24, 12, default);
INSERT INTO meals_restaurant VALUES (24, 13, default);
INSERT INTO meals_restaurant VALUES (28, 13, default);
INSERT INTO meals_restaurant VALUES (28, 14, default);
INSERT INTO meals_restaurant VALUES (36, 13, default);
INSERT INTO meals_restaurant VALUES (39, 9, default);
INSERT INTO meals_restaurant VALUES (34, 7, default);
INSERT INTO meals_restaurant VALUES (41, 16, default);
INSERT INTO meals_restaurant VALUES (51, 21, default);
INSERT INTO meals_restaurant VALUES (49, 18, default);
INSERT INTO meals_restaurant VALUES (42, 17, default);
INSERT INTO meals_restaurant VALUES (53, 22, default);
INSERT INTO meals_restaurant VALUES (46, 20, default);
INSERT INTO meals_restaurant VALUES (53, 23, default);
INSERT INTO meals_restaurant VALUES (59, 18, default);
INSERT INTO meals_restaurant VALUES (48, 23, default);
INSERT INTO meals_restaurant VALUES (55, 20, default);
INSERT INTO meals_restaurant VALUES (50, 23, default);
INSERT INTO meals_restaurant VALUES (44, 16, default);
INSERT INTO meals_restaurant VALUES (50, 22, default);
INSERT INTO meals_restaurant VALUES (45, 21, default);
INSERT INTO meals_restaurant VALUES (40, 21, default);
INSERT INTO meals_restaurant VALUES (40, 23, default);
INSERT INTO meals_restaurant VALUES (55, 15, default);
INSERT INTO meals_restaurant VALUES (61, 15, default);
INSERT INTO meals_restaurant VALUES (60, 20, default);
INSERT INTO meals_restaurant VALUES (48, 15, default);
INSERT INTO meals_restaurant VALUES (47, 23, default);
INSERT INTO meals_restaurant VALUES (51, 20, default);
INSERT INTO meals_restaurant VALUES (49, 22, default);
INSERT INTO meals_restaurant VALUES (58, 20, default);
INSERT INTO meals_restaurant VALUES (45, 17, default);
INSERT INTO meals_restaurant VALUES (51, 19, default);
INSERT INTO meals_restaurant VALUES (49, 20, default);
INSERT INTO meals_restaurant VALUES (52, 23, default);
INSERT INTO meals_restaurant VALUES (62, 21, default);
INSERT INTO meals_restaurant VALUES (44, 21, default);
INSERT INTO meals_restaurant VALUES (43, 16, default);
INSERT INTO meals_restaurant VALUES (46, 23, default);
INSERT INTO meals_restaurant VALUES (58, 22, default);
INSERT INTO meals_restaurant VALUES (58, 18, default);
INSERT INTO meals_restaurant VALUES (44, 22, default);
INSERT INTO meals_restaurant VALUES (40, 18, default);
INSERT INTO meals_restaurant VALUES (59, 15, default);
INSERT INTO meals_restaurant VALUES (49, 23, default);
INSERT INTO meals_restaurant VALUES (55, 23, default);
INSERT INTO meals_restaurant VALUES (42, 20, default);
INSERT INTO meals_restaurant VALUES (50, 19, default);
INSERT INTO meals_restaurant VALUES (45, 15, default);
INSERT INTO meals_restaurant VALUES (50, 18, default);
INSERT INTO meals_restaurant VALUES (48, 17, default);
INSERT INTO meals_restaurant VALUES (64, 25, default);
INSERT INTO meals_restaurant VALUES (73, 27, default);
INSERT INTO meals_restaurant VALUES (78, 30, default);
INSERT INTO meals_restaurant VALUES (71, 30, default);
INSERT INTO meals_restaurant VALUES (65, 29, default);
INSERT INTO meals_restaurant VALUES (65, 28, default);
INSERT INTO meals_restaurant VALUES (79, 29, default);
INSERT INTO meals_restaurant VALUES (74, 26, default);
INSERT INTO meals_restaurant VALUES (80, 26, default);
INSERT INTO meals_restaurant VALUES (68, 30, default);
INSERT INTO meals_restaurant VALUES (69, 26, default);
INSERT INTO meals_restaurant VALUES (76, 25, default);
INSERT INTO meals_restaurant VALUES (63, 29, default);
INSERT INTO meals_restaurant VALUES (66, 29, default);
INSERT INTO meals_restaurant VALUES (79, 24, default);
INSERT INTO meals_restaurant VALUES (75, 27, default);
INSERT INTO meals_restaurant VALUES (75, 28, default);
INSERT INTO meals_restaurant VALUES (76, 26, default);
INSERT INTO meals_restaurant VALUES (64, 29, default);
INSERT INTO meals_restaurant VALUES (77, 24, default);
INSERT INTO meals_restaurant VALUES (79, 25, default);
INSERT INTO meals_restaurant VALUES (72, 25, default);
INSERT INTO meals_restaurant VALUES (75, 25, default);
INSERT INTO meals_restaurant VALUES (71, 27, default);
INSERT INTO meals_restaurant VALUES (74, 25, default);
INSERT INTO meals_restaurant VALUES (65, 30, default);
INSERT INTO meals_restaurant VALUES (76, 24, default);
INSERT INTO meals_restaurant VALUES (73, 28, default);
INSERT INTO meals_restaurant VALUES (77, 25, default);
INSERT INTO meals_restaurant VALUES (68, 27, default);
INSERT INTO meals_restaurant VALUES (78, 24, default);
INSERT INTO meals_restaurant VALUES (68, 25, default);
INSERT INTO meals_restaurant VALUES (67, 27, default);
INSERT INTO meals_restaurant VALUES (70, 27, default);
INSERT INTO meals_restaurant VALUES (69, 27, default);
INSERT INTO meals_restaurant VALUES (73, 26, default);
INSERT INTO meals_restaurant VALUES (80, 29, default);
INSERT INTO meals_restaurant VALUES (80, 28, default);
INSERT INTO meals_restaurant VALUES (73, 25, default);
INSERT INTO meals_restaurant VALUES (66, 24, default);
INSERT INTO meals_restaurant VALUES (82, 32, default);
INSERT INTO meals_restaurant VALUES (89, 33, default);
INSERT INTO meals_restaurant VALUES (95, 33, default);
INSERT INTO meals_restaurant VALUES (86, 34, default);
INSERT INTO meals_restaurant VALUES (83, 35, default);
INSERT INTO meals_restaurant VALUES (94, 31, default);
INSERT INTO meals_restaurant VALUES (92, 36, default);
INSERT INTO meals_restaurant VALUES (90, 34, default);
INSERT INTO meals_restaurant VALUES (83, 31, default);
INSERT INTO meals_restaurant VALUES (82, 35, default);
INSERT INTO meals_restaurant VALUES (96, 34, default);
INSERT INTO meals_restaurant VALUES (81, 34, default);
INSERT INTO meals_restaurant VALUES (89, 34, default);
INSERT INTO meals_restaurant VALUES (91, 33, default);
INSERT INTO meals_restaurant VALUES (85, 33, default);
INSERT INTO meals_restaurant VALUES (82, 36, default);
INSERT INTO meals_restaurant VALUES (83, 36, default);
INSERT INTO meals_restaurant VALUES (86, 31, default);
INSERT INTO meals_restaurant VALUES (93, 36, default);
INSERT INTO meals_restaurant VALUES (88, 34, default);
INSERT INTO meals_restaurant VALUES (89, 32, default);
INSERT INTO meals_restaurant VALUES (89, 35, default);
INSERT INTO meals_restaurant VALUES (87, 35, default);
INSERT INTO meals_restaurant VALUES (96, 33, default);
INSERT INTO meals_restaurant VALUES (82, 34, default);
INSERT INTO meals_restaurant VALUES (93, 35, default);
INSERT INTO meals_restaurant VALUES (95, 36, default);
INSERT INTO meals_restaurant VALUES (83, 32, default);
INSERT INTO meals_restaurant VALUES (86, 35, default);
INSERT INTO meals_restaurant VALUES (91, 34, default);
INSERT INTO meals_restaurant VALUES (90, 31, default);
INSERT INTO meals_restaurant VALUES (93, 33, default);
INSERT INTO meals_restaurant VALUES (92, 31, default);
INSERT INTO meals_restaurant VALUES (89, 31, default);
INSERT INTO meals_restaurant VALUES (91, 36, default);
INSERT INTO meals_restaurant VALUES (82, 31, default);
INSERT INTO meals_restaurant VALUES (91, 32, default);
INSERT INTO meals_restaurant VALUES (86, 33, default);
INSERT INTO meals_restaurant VALUES (98, 38, default);
INSERT INTO meals_restaurant VALUES (111, 41, default);
INSERT INTO meals_restaurant VALUES (105, 41, default);
INSERT INTO meals_restaurant VALUES (109, 43, default);
INSERT INTO meals_restaurant VALUES (100, 39, default);
INSERT INTO meals_restaurant VALUES (116, 41, default);
INSERT INTO meals_restaurant VALUES (97, 41, default);
INSERT INTO meals_restaurant VALUES (117, 39, default);
INSERT INTO meals_restaurant VALUES (113, 41, default);
INSERT INTO meals_restaurant VALUES (112, 43, default);
INSERT INTO meals_restaurant VALUES (101, 42, default);
INSERT INTO meals_restaurant VALUES (101, 43, default);
INSERT INTO meals_restaurant VALUES (109, 41, default);
INSERT INTO meals_restaurant VALUES (117, 40, default);
INSERT INTO meals_restaurant VALUES (108, 39, default);
INSERT INTO meals_restaurant VALUES (106, 42, default);
INSERT INTO meals_restaurant VALUES (113, 39, default);
INSERT INTO meals_restaurant VALUES (102, 39, default);
INSERT INTO meals_restaurant VALUES (103, 37, default);
INSERT INTO meals_restaurant VALUES (106, 40, default);
INSERT INTO meals_restaurant VALUES (107, 43, default);
INSERT INTO meals_restaurant VALUES (97, 43, default);
INSERT INTO meals_restaurant VALUES (118, 41, default);
INSERT INTO meals_restaurant VALUES (107, 39, default);
INSERT INTO meals_restaurant VALUES (113, 42, default);
INSERT INTO meals_restaurant VALUES (111, 37, default);
INSERT INTO meals_restaurant VALUES (104, 38, default);
INSERT INTO meals_restaurant VALUES (99, 41, default);
INSERT INTO meals_restaurant VALUES (115, 38, default);
INSERT INTO meals_restaurant VALUES (105, 42, default);
INSERT INTO meals_restaurant VALUES (99, 39, default);
INSERT INTO meals_restaurant VALUES (97, 37, default);
INSERT INTO meals_restaurant VALUES (114, 38, default);
INSERT INTO meals_restaurant VALUES (108, 41, default);
INSERT INTO meals_restaurant VALUES (97, 40, default);
INSERT INTO meals_restaurant VALUES (105, 40, default);
INSERT INTO meals_restaurant VALUES (107, 41, default);
INSERT INTO meals_restaurant VALUES (111, 40, default);
INSERT INTO meals_restaurant VALUES (109, 40, default);
INSERT INTO meals_restaurant VALUES (114, 42, default);
INSERT INTO meals_restaurant VALUES (103, 40, default);
INSERT INTO meals_restaurant VALUES (100, 41, default);
INSERT INTO meals_restaurant VALUES (120, 45, default);
INSERT INTO meals_restaurant VALUES (125, 48, default);
INSERT INTO meals_restaurant VALUES (122, 45, default);
INSERT INTO meals_restaurant VALUES (127, 44, default);
INSERT INTO meals_restaurant VALUES (129, 49, default);
INSERT INTO meals_restaurant VALUES (130, 44, default);
INSERT INTO meals_restaurant VALUES (123, 45, default);
INSERT INTO meals_restaurant VALUES (126, 47, default);
INSERT INTO meals_restaurant VALUES (121, 50, default);
INSERT INTO meals_restaurant VALUES (127, 45, default);
INSERT INTO meals_restaurant VALUES (122, 48, default);
INSERT INTO meals_restaurant VALUES (120, 47, default);
INSERT INTO meals_restaurant VALUES (124, 44, default);
INSERT INTO meals_restaurant VALUES (119, 50, default);
INSERT INTO meals_restaurant VALUES (128, 44, default);
INSERT INTO meals_restaurant VALUES (125, 44, default);
INSERT INTO meals_restaurant VALUES (121, 44, default);
INSERT INTO meals_restaurant VALUES (120, 49, default);
INSERT INTO meals_restaurant VALUES (131, 46, default);
INSERT INTO meals_restaurant VALUES (130, 45, default);
INSERT INTO meals_restaurant VALUES (127, 49, default);
INSERT INTO meals_restaurant VALUES (124, 46, default);
INSERT INTO meals_restaurant VALUES (130, 46, default);
INSERT INTO meals_restaurant VALUES (128, 47, default);
INSERT INTO meals_restaurant VALUES (126, 44, default);
INSERT INTO meals_restaurant VALUES (128, 50, default);
INSERT INTO meals_restaurant VALUES (129, 44, default);
INSERT INTO meals_restaurant VALUES (132, 48, default);
INSERT INTO meals_restaurant VALUES (119, 44, default);
INSERT INTO meals_restaurant VALUES (129, 45, default);
INSERT INTO meals_restaurant VALUES (129, 48, default);
INSERT INTO meals_restaurant VALUES (127, 48, default);
INSERT INTO meals_restaurant VALUES (129, 50, default);
INSERT INTO meals_restaurant VALUES (123, 49, default);
INSERT INTO meals_restaurant VALUES (120, 50, default);
INSERT INTO meals_restaurant VALUES (130, 49, default);
INSERT INTO meals_restaurant VALUES (131, 50, default);
INSERT INTO meals_restaurant VALUES (122, 44, default);
INSERT INTO meals_restaurant VALUES (119, 47, default);
INSERT INTO meals_restaurant VALUES (130, 50, default);
INSERT INTO meals_restaurant VALUES (125, 46, default);
INSERT INTO meals_restaurant VALUES (123, 47, default);
INSERT INTO meals_restaurant VALUES (134, 52, default);
INSERT INTO meals_restaurant VALUES (144, 52, default);
INSERT INTO meals_restaurant VALUES (133, 51, default);
INSERT INTO meals_restaurant VALUES (142, 57, default);
INSERT INTO meals_restaurant VALUES (140, 51, default);
INSERT INTO meals_restaurant VALUES (148, 57, default);
INSERT INTO meals_restaurant VALUES (144, 56, default);
INSERT INTO meals_restaurant VALUES (145, 52, default);
INSERT INTO meals_restaurant VALUES (133, 57, default);
INSERT INTO meals_restaurant VALUES (134, 55, default);
INSERT INTO meals_restaurant VALUES (142, 54, default);
INSERT INTO meals_restaurant VALUES (148, 55, default);
INSERT INTO meals_restaurant VALUES (147, 51, default);
INSERT INTO meals_restaurant VALUES (147, 52, default);
INSERT INTO meals_restaurant VALUES (134, 56, default);
INSERT INTO meals_restaurant VALUES (136, 55, default);
INSERT INTO meals_restaurant VALUES (144, 51, default);
INSERT INTO meals_restaurant VALUES (147, 54, default);
INSERT INTO meals_restaurant VALUES (135, 54, default);
INSERT INTO meals_restaurant VALUES (147, 57, default);
INSERT INTO meals_restaurant VALUES (138, 52, default);
INSERT INTO meals_restaurant VALUES (140, 56, default);
INSERT INTO meals_restaurant VALUES (146, 51, default);
INSERT INTO meals_restaurant VALUES (139, 52, default);
INSERT INTO meals_restaurant VALUES (133, 52, default);
INSERT INTO meals_restaurant VALUES (137, 55, default);
INSERT INTO meals_restaurant VALUES (147, 56, default);
INSERT INTO meals_restaurant VALUES (140, 55, default);
INSERT INTO meals_restaurant VALUES (143, 53, default);
INSERT INTO meals_restaurant VALUES (139, 53, default);
INSERT INTO meals_restaurant VALUES (143, 52, default);
INSERT INTO meals_restaurant VALUES (136, 51, default);
INSERT INTO meals_restaurant VALUES (136, 56, default);
INSERT INTO meals_restaurant VALUES (141, 55, default);
INSERT INTO meals_restaurant VALUES (133, 56, default);
INSERT INTO meals_restaurant VALUES (149, 51, default);
INSERT INTO meals_restaurant VALUES (134, 54, default);
INSERT INTO meals_restaurant VALUES (145, 54, default);
INSERT INTO meals_restaurant VALUES (138, 55, default);
INSERT INTO meals_restaurant VALUES (137, 54, default);
INSERT INTO meals_restaurant VALUES (138, 51, default);
INSERT INTO meals_restaurant VALUES (146, 56, default);
INSERT INTO meals_restaurant VALUES (137, 53, default);
INSERT INTO meals_restaurant VALUES (133, 55, default);
INSERT INTO meals_restaurant VALUES (138, 56, default);
INSERT INTO meals_restaurant VALUES (152, 59, default);
INSERT INTO meals_restaurant VALUES (152, 62, default);
INSERT INTO meals_restaurant VALUES (154, 64, default);
INSERT INTO meals_restaurant VALUES (158, 60, default);
INSERT INTO meals_restaurant VALUES (161, 61, default);
INSERT INTO meals_restaurant VALUES (164, 61, default);
INSERT INTO meals_restaurant VALUES (163, 63, default);
INSERT INTO meals_restaurant VALUES (157, 63, default);
INSERT INTO meals_restaurant VALUES (159, 60, default);
INSERT INTO meals_restaurant VALUES (167, 63, default);
INSERT INTO meals_restaurant VALUES (156, 63, default);
INSERT INTO meals_restaurant VALUES (156, 65, default);
INSERT INTO meals_restaurant VALUES (156, 64, default);
INSERT INTO meals_restaurant VALUES (151, 60, default);
INSERT INTO meals_restaurant VALUES (169, 65, default);
INSERT INTO meals_restaurant VALUES (165, 58, default);
INSERT INTO meals_restaurant VALUES (163, 61, default);
INSERT INTO meals_restaurant VALUES (152, 65, default);
INSERT INTO meals_restaurant VALUES (166, 63, default);
INSERT INTO meals_restaurant VALUES (170, 62, default);
INSERT INTO meals_restaurant VALUES (157, 65, default);
INSERT INTO meals_restaurant VALUES (153, 63, default);
INSERT INTO meals_restaurant VALUES (162, 60, default);
INSERT INTO meals_restaurant VALUES (160, 60, default);
INSERT INTO meals_restaurant VALUES (160, 61, default);
INSERT INTO meals_restaurant VALUES (152, 60, default);
INSERT INTO meals_restaurant VALUES (155, 62, default);
INSERT INTO meals_restaurant VALUES (154, 58, default);
INSERT INTO meals_restaurant VALUES (160, 64, default);
INSERT INTO meals_restaurant VALUES (168, 59, default);
INSERT INTO meals_restaurant VALUES (170, 61, default);
INSERT INTO meals_restaurant VALUES (156, 58, default);
INSERT INTO meals_restaurant VALUES (153, 59, default);
INSERT INTO meals_restaurant VALUES (158, 65, default);
INSERT INTO meals_restaurant VALUES (152, 63, default);
INSERT INTO meals_restaurant VALUES (160, 59, default);
INSERT INTO meals_restaurant VALUES (153, 58, default);
INSERT INTO meals_restaurant VALUES (169, 62, default);
INSERT INTO meals_restaurant VALUES (158, 62, default);
INSERT INTO meals_restaurant VALUES (165, 65, default);
INSERT INTO meals_restaurant VALUES (165, 62, default);
INSERT INTO meals_restaurant VALUES (166, 62, default);
INSERT INTO meals_restaurant VALUES (157, 62, default);
INSERT INTO meals_restaurant VALUES (161, 62, default);
INSERT INTO meals_restaurant VALUES (172, 67, default);
INSERT INTO meals_restaurant VALUES (184, 70, default);
INSERT INTO meals_restaurant VALUES (185, 66, default);
INSERT INTO meals_restaurant VALUES (176, 70, default);
INSERT INTO meals_restaurant VALUES (172, 72, default);
INSERT INTO meals_restaurant VALUES (181, 72, default);
INSERT INTO meals_restaurant VALUES (186, 72, default);
INSERT INTO meals_restaurant VALUES (185, 70, default);
INSERT INTO meals_restaurant VALUES (177, 67, default);
INSERT INTO meals_restaurant VALUES (174, 66, default);
INSERT INTO meals_restaurant VALUES (173, 69, default);
INSERT INTO meals_restaurant VALUES (174, 69, default);
INSERT INTO meals_restaurant VALUES (176, 66, default);
INSERT INTO meals_restaurant VALUES (177, 71, default);
INSERT INTO meals_restaurant VALUES (185, 69, default);
INSERT INTO meals_restaurant VALUES (177, 68, default);
INSERT INTO meals_restaurant VALUES (183, 69, default);
INSERT INTO meals_restaurant VALUES (182, 70, default);
INSERT INTO meals_restaurant VALUES (187, 68, default);
INSERT INTO meals_restaurant VALUES (181, 66, default);
INSERT INTO meals_restaurant VALUES (182, 71, default);
INSERT INTO meals_restaurant VALUES (174, 70, default);
INSERT INTO meals_restaurant VALUES (178, 68, default);
INSERT INTO meals_restaurant VALUES (180, 67, default);
INSERT INTO meals_restaurant VALUES (172, 68, default);
INSERT INTO meals_restaurant VALUES (186, 67, default);
INSERT INTO meals_restaurant VALUES (173, 66, default);
INSERT INTO meals_restaurant VALUES (176, 69, default);
INSERT INTO meals_restaurant VALUES (181, 71, default);
INSERT INTO meals_restaurant VALUES (187, 70, default);
INSERT INTO meals_restaurant VALUES (183, 68, default);
INSERT INTO meals_restaurant VALUES (183, 67, default);
INSERT INTO meals_restaurant VALUES (176, 67, default);
INSERT INTO meals_restaurant VALUES (178, 67, default);
INSERT INTO meals_restaurant VALUES (171, 70, default);
INSERT INTO meals_restaurant VALUES (184, 69, default);
INSERT INTO meals_restaurant VALUES (186, 70, default);
INSERT INTO meals_restaurant VALUES (173, 71, default);
INSERT INTO meals_restaurant VALUES (180, 72, default);
INSERT INTO meals_restaurant VALUES (172, 70, default);
INSERT INTO meals_restaurant VALUES (179, 69, default);
INSERT INTO meals_restaurant VALUES (174, 67, default);
INSERT INTO meals_restaurant VALUES (182, 66, default);
INSERT INTO meals_restaurant VALUES (174, 72, default);
INSERT INTO meals_restaurant VALUES (181, 67, default);










